### ISSUE TITLE
Add client side form validation

### ISSUE THREAD

**Issue by v0idzz** [mypolitics/mypolitics-3#122]
User should receive instant feedback whether the entered values are correct. For example, on the screenshot below there should be a message that the email and password are both invalid. This can be easily done with [Yup](https://github.com/jquense/yup).
![obraz](https://user-images.githubusercontent.com/12448522/113475229-83021100-9474-11eb-927a-9a00ff4ccfbb.png)

**Comment by xxczaki** [comment]
Closed by #127.
