### ISSUE TITLE
Navbar items shake on scroll

### ISSUE THREAD

**Issue by v0idzz** [mypolitics/mypolitics-3#128]
Hardly a major issue, but quite annoying one.
### Environment
Browser: Firefox 87.0
### Steps to reproduce
1. Scroll from top to bottom and vice versa.
Result:
![Peek 2021-04-05 00-34](https://user-images.githubusercontent.com/12448522/113523248-eb510f80-95a6-11eb-847c-5e89e81fea8f.gif)

**Comment by xxczaki** [comment]
Couldn't reproduce on Firefox Developer Edition (88.0b7 (64-bit), aurora update channel).

**Comment by v0idzz** [comment]
Happens to me on both Chromium and Firefox. I've just tested the browser you mentioned and I can easily reproduce the issue there, so I suppose the issue is related to the underlying platform.
![Peek 2021-04-06 11-56](https://user-images.githubusercontent.com/12448522/113693692-28b0bc80-96cf-11eb-87ba-39d841d0d6e9.gif)
