### ISSUE TITLE
Fix QuizLink design

### ISSUE THREAD

**Issue by AdrianOrlow** [mypolitics/mypolitics-3#70]
Make features inline
![image](https://user-images.githubusercontent.com/10941338/111908282-eb0a2d80-8a58-11eb-8c04-6252117931bf.png)

**Comment by v0idzz** [comment]
![obraz](https://user-images.githubusercontent.com/12448522/111961018-c6fa2b00-8af0-11eb-95fd-035f1606a8f9.png)
That's how it looks like with `flex-wrap: wrap`. Thoughts?
